[project]
authors = ["Matt Auer"]
entry = "main.sw"
license = "Apache-2.0"
name = "custom_asset"

[dependencies]
src20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.3.2" }
src3 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.3.2" }
token = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.17.2" }
