[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "token_contract"

[dependencies]
string = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.6.0" }
