name: GitHub Pages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: Build
        env:
          CI: false
          NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secret.ALGOLIA_APP_ID }}
          NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY: ${{ secret.ALGOLIA_SEARCH_API_KEY }}
          ALGOLIA_SEARCH_ADMIN_KEY: ${{ secret.ALGOLIA_API_KEY }}
          VITE_FUEL_PROVIDER_URL: "https://node-beta-1.fuel.network/graphql"
          VITE_FUEL_FAUCET_URL: "https://faucet-beta-1.fuel.network/dispense"
          VITE_FAUCET_RECAPTCHA_KEY: "6Ld3cEwfAAAAAMd4QTs7aO85LyKGdgj0bFsdBfre"
          VITE_MNEMONIC_WORDS: 12
          DOCS_BASE_URL: "/${{ github.event.repository.name }}"
          NEXT_PUBLIC_APP_URL: "https://fuels-wallet.vercel.app/app/"
          NEXT_PUBLIC_STORYBOOK_URL: "https://fuels-wallet.vercel.app/storybook/"
          NEXT_PUBLIC_WALLET_DOWNLOAD_URL: "https://fuels-wallet.vercel.app/app/fuel-wallet.zip"
        run: |
          pnpm install
          pnpm build:preview

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          clean: true
          branch: gh-pages
          folder: ./dist
