name: "Unpublish old versions"

on:
  workflow_dispatch:
    inputs:
      delete_packages:
        type: boolean
        description: Delete packages? otherwise dry-run mode will be used
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clean-npm-versions:
    name: Unpublish versions next, preview, master...
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - uses: FuelLabs/github-actions/setups/node/action.yaml@58bcd91d7246e40938e1971be0b0fe35b253dff0
        with:
          node-version: 20.11.0
          pnpm-version: 9.5.0
      - uses: FuelLabs/github-actions/setups/npm@master
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
      - run: |
          node ./scripts/unpublish.js
        env:
          DELETE_PACKAGES: ${{ github.event.inputs.delete_packages}}
